### ISSUE TITLE
Caching support for the chart

### ISSUE THREAD

**Issue by shaikatz** [unguiculus/loki-helm-chart#11]
Thanks for the great work on that chart,
I will be happy to start using it instead of the complicated JSONNET installation, but I feel that cache support is required in order to prevent regression in my setup.

Do you have any ETA when you gonna add cache support for that chart?

**Comment by unguiculus** [comment]
Thanks @shaikatz. I don't use caching yet. I'll try and look into it, but it's not the most pressing thing for me at the moment. Are you using Redis or Memcached?

**Comment by shaikatz** [comment]
Thanks @unguiculus for closing that, I'll try to migrate my workloads to use this chart as soon as I'll have the capacity for that, really looking forward to dropping the JSONNET piece from my infrastructure.
