### ISSUE TITLE
Set config as yaml not as string

### ISSUE THREAD

**Issue by tarvip** [unguiculus/loki-helm-chart#9]
Just an idea.
Official monolith helm chart uses a bit different approach when setting Loki `config`:
[values.yaml](https://github.com/grafana/loki/blob/21addf79351477c061afdea566dcce175d80a396/production/helm/loki/values.yaml#L46)
[secret.yaml](https://github.com/grafana/loki/blob/21addf79351477c061afdea566dcce175d80a396/production/helm/loki/templates/secret.yaml#L12)

In this case it is possible to use `helmfile` and have one main config and override some values for different environments, at the moment it is not possible.

**Comment by unguiculus** [comment]
Actually, I played with this and decided against it. See the note in the readme about that:
https://github.com/unguiculus/loki-helm-chart/tree/master/charts/loki#example-configuration-using-memberlist-boltdb-shipper-and-s3-for-storage

I did not want to bury a somewhat random default config in the chart. I think it is a good thing if you have to specify the complete config externally. Templating is supported, so you can easily extract environment-specific values that you need to override.

That being said, I'm open for ideas and may revisit this at some point.

**Comment by tarvip** [comment]
Thanks for explaining.
